# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build & Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run wizard
        run: |
          npx quorum-wizard -q
          cd network/3-nodes-quickstart
          ./start.sh
          cd -
      - name: Build and Test Cakeshop
        run: mvn clean package
      - name: Make WAR available
          uses: actions/upload-artifact@v2
          with:
              name: cakeshop
              path: cakeshop-api/target/*.war
